In [1]:
#load all important libaries
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt #data visualisation
import seaborn as sns
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))


/kaggle/input/loan-prediction-problem-dataset/test_Y3wMUE5_7gLdaTN.csv
/kaggle/input/loan-prediction-problem-dataset/train_u6lujuX_CVtuZ9i.csv


In [2]:
#get the dataset
df = pd.read_csv('../input/loan-prediction-problem-dataset/train_u6lujuX_CVtuZ9i.csv')
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

# simple look on data

In [3]:
df.isnull().sum(), df.shape

(Loan_ID               0
 Gender               13
 Married               3
 Dependents           15
 Education             0
 Self_Employed        32
 ApplicantIncome       0
 CoapplicantIncome     0
 LoanAmount           22
 Loan_Amount_Term     14
 Credit_History       50
 Property_Area         0
 Loan_Status           0
 dtype: int64,
 (614, 13))

In [4]:
df.drop(columns=['Loan_ID'], inplace = True)

# loan id doesnt give any unique information so we can drop it

In [5]:
df.duplicated().any()
#check for duplicate values

False

In [6]:
df.Loan_Status.value_counts()

Y    422
N    192
Name: Loan_Status, dtype: int64

# more insight on data

In [7]:
#we can see that y is about double in comparision of n

yes = df[df['Loan_Status']== 'Y']
no = df[df['Loan_Status']== 'N']
count1 = yes.Gender.value_counts()
count2=no.Gender.value_counts()
count1,count2

(Male      339
 Female     75
 Name: Gender, dtype: int64,
 Male      150
 Female     37
 Name: Gender, dtype: int64)

In [8]:
# most male and female have loan.

count1 = yes.Married.value_counts()
count2=no.Married.value_counts()
count1,count2

(Yes    285
 No     134
 Name: Married, dtype: int64,
 Yes    113
 No      79
 Name: Married, dtype: int64)

In [9]:

count1 = yes.Dependents.value_counts()
count2=no.Dependents.value_counts()
count1,count2

(0     238
 2      76
 1      66
 3+     33
 Name: Dependents, dtype: int64,
 0     107
 1      36
 2      25
 3+     18
 Name: Dependents, dtype: int64)

In [10]:


count1 = yes.Education.value_counts()
count2=no.Education.value_counts()
count1,count2

(Graduate        340
 Not Graduate     82
 Name: Education, dtype: int64,
 Graduate        140
 Not Graduate     52
 Name: Education, dtype: int64)

In [11]:
#graduate poeple are more likely to get a laon Self_Employed


count1 = yes.Self_Employed.value_counts()
count2=no.Self_Employed.value_counts()
count1,count2

(No     343
 Yes     56
 Name: Self_Employed, dtype: int64,
 No     157
 Yes     26
 Name: Self_Employed, dtype: int64)

In [12]:
df.columns

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [13]:
count1 = yes.Credit_History.value_counts()
count2=no.Credit_History.value_counts()
count1,count2

(1.0    378
 0.0      7
 Name: Credit_History, dtype: int64,
 1.0    97
 0.0    82
 Name: Credit_History, dtype: int64)

In [14]:
#poeple with credit history are more likely to get a loan

count1 = yes.Property_Area.value_counts()
count2=no.Property_Area.value_counts()
count1,count2

(Semiurban    179
 Urban        133
 Rural        110
 Name: Property_Area, dtype: int64,
 Rural        69
 Urban        69
 Semiurban    54
 Name: Property_Area, dtype: int64)

# handling missing value

In [15]:
def missin_val(df, col):
    cate = ['Gender','Married','Dependents','Education','Self_Employed','Credit_History','Property_Area']
    if col in cate:
        df[col] = df[col].fillna(df[col].value_counts().index[0])
    else:
        df[col] = df[col].fillna(df[col].mean())
    return df
        

In [16]:
df.head()

Gender Married Dependents     Education Self_Employed  ApplicantIncome  \
0   Male      No          0      Graduate            No             5849   
1   Male     Yes          1      Graduate            No             4583   
2   Male     Yes          0      Graduate           Yes             3000   
3   Male     Yes          0  Not Graduate            No             2583   
4   Male      No          0      Graduate            No             6000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0         NaN             360.0             1.0   
1             1508.0       128.0             360.0             1.0   
2                0.0        66.0             360.0             1.0   
3             2358.0       120.0             360.0             1.0   
4                0.0       141.0             360.0             1.0   

  Property_Area Loan_Status  
0         Urban           Y  
1         Rural           N  
2         Urban           Y  
3         Urban           Y  
4         Urban           Y

In [17]:
li = df.isnull().sum()

for key in li.keys():
    if li[key] > 0:
        df = missin_val(df, key)

In [18]:
df.isnull().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [19]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
cate = ['Gender','Married','Dependents','Education','Self_Employed','Credit_History','Property_Area','Loan_Status']  

for col in cate:
    df[col] = encoder.fit_transform(df[col])

df.head()

Gender  Married  Dependents  Education  Self_Employed  ApplicantIncome  \
0       1        0           0          0              0             5849   
1       1        1           1          0              0             4583   
2       1        1           0          0              1             3000   
3       1        1           0          1              0             2583   
4       1        0           0          0              0             6000   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Credit_History  \
0                0.0  146.412162             360.0               1   
1             1508.0  128.000000             360.0               1   
2                0.0   66.000000             360.0               1   
3             2358.0  120.000000             360.0               1   
4                0.0  141.000000             360.0               1   

   Property_Area  Loan_Status  
0              2            1  
1              0            0  
2              2            1  
3              2            1  
4              2            1

In [20]:
x = df.drop(columns =['Loan_Status'])
y = df['Loan_Status']

In [21]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

In [22]:
models = {
    'LogisticRegression': LogisticRegression(random_state=42, max_iter= 1000),
    'KNeighborsClassifier': KNeighborsClassifier(),
    'SVC': SVC(random_state=42),
    'DecisionTreeClassifier': DecisionTreeClassifier(criterion="gini", max_depth = 1, random_state=42),
    'DecisionTreeClassifier2': DecisionTreeClassifier(criterion="entropy",max_depth = 1, random_state=42)
}

In [23]:
cv =  StratifiedShuffleSplit(n_splits=5, test_size=0.2, random_state= 42)

In [24]:
from sklearn.model_selection import cross_val_score

def eval_model(models, X, y):
    for name, model in models.items():
        print(name,':')
        score = np.array(cross_val_score(model,x,y, cv=cv))
        print(score.mean())
        print(score)
        print('*'*30)
        
eval_model(models, x, y)

LogisticRegression :
0.8016260162601627
[0.86178862 0.77235772 0.7804878  0.82113821 0.77235772]
******************************
KNeighborsClassifier :
0.6308943089430894
[0.6504065  0.63414634 0.62601626 0.61788618 0.62601626]
******************************
SVC :
0.6878048780487805
[0.69105691 0.69105691 0.69105691 0.68292683 0.68292683]
******************************
DecisionTreeClassifier :
0.8032520325203251
[0.85365854 0.77235772 0.7804878  0.82926829 0.7804878 ]
******************************
DecisionTreeClassifier2 :
0.8032520325203251
[0.85365854 0.77235772 0.7804878  0.82926829 0.7804878 ]
******************************


we can see that logistic regression or dtc (both entorpy and gini) are good algorithm for this dataset.

we will use dtc.

In [25]:
DTC = DecisionTreeClassifier(criterion="gini", max_depth = 1, random_state=42)

In [29]:
score = np.array(cross_val_score(DTC,x,y, cv=cv))
print(score.mean())
print(score)
print('*'*30)

0.8032520325203251
[0.85365854 0.77235772 0.7804878  0.82926829 0.7804878 ]
******************************
